# Generated by Django 5.2.17 on 2026-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_city_user_country_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='state',
        ),
    ]
