# Generated by Django 5.2.17 on 2026-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_cart_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_wishlist_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
