# Generated by Django 5.2.17 on 2026-09-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_no_of_cart_items_user_no_of_wishlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_of_cart_items',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_wishlist_items',
        ),
    ]
