# Generated by Django 5.2.17 on 2026-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0011_move_user_address_to_address_book'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_host', True)), fields=('is_host',), name='only_one_host'),
        ),
    ]
