# Generated by Django 5.2.17 on 2026-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='only_for_new',
            field=models.BooleanField(default=False),
        ),
    ]
