# Generated by Django 5.2.17 on 2026-09-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsnapshot',
            name='checkouts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
